version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # Location of your requirements.txt
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"  # GitHub Actions are in the root .github/workflows
    schedule:
      interval: "weekly"
